#!/usr/bin/env bash
# code-generator — Generate boilerplate code for common patterns
set -euo pipefail

VERSION="2.0.0"
DATA_DIR="${CODE_GEN_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/code-generator}"
mkdir -p "$DATA_DIR"

show_help() {
    cat << EOF
code-generator v$VERSION

Usage: code-generator <command> [args]

Generators:
  class <name> [lang]         Generate class skeleton (py|js|ts|java|go)
  api <name> [framework]      REST API endpoint (flask|express|fastapi)
  cli <name> [lang]           CLI tool scaffold (bash|python|node)
  model <name> <fields...>    Data model with validation
  test <name> [framework]     Test file (pytest|jest|go)
  crud <name> <fields...>     Full CRUD operations
  config <format>             Config file template (yaml|toml|json|ini)
  docker <lang>               Dockerfile + compose for a stack
  readme <project>            README.md template
  gitignore <lang>            .gitignore for language/framework

Utils:
  snippet <lang> <pattern>    Common code snippets
  license <type>              Generate LICENSE file (mit|apache|gpl)
  history                     Recently generated files
  help                        Show this help

EOF
}

cmd_class() {
    local name="${1:?Usage: code-generator class <name> [lang]}"
    local lang="${2:-python}"
    
    case "$lang" in
        py|python)
            cat << PYEOF
class ${name^}:
    """${name^} - generated by code-generator."""
    
    def __init__(self, **kwargs):
        self._data = kwargs
    
    def __repr__(self):
        attrs = ", ".join(f"{k}={v!r}" for k, v in self._data.items())
        return f"${name^}({attrs})"
    
    def to_dict(self):
        return dict(self._data)
    
    @classmethod
    def from_dict(cls, data: dict):
        return cls(**data)
    
    def validate(self):
        """Override in subclass to add validation."""
        return True
PYEOF
            ;;
        js|javascript)
            cat << JSEOF
class ${name^} {
  constructor(options = {}) {
    this.options = options;
    this.createdAt = new Date();
  }

  toJSON() {
    return { ...this.options, createdAt: this.createdAt };
  }

  static from(data) {
    return new ${name^}(data);
  }

  validate() {
    return true;
  }

  toString() {
    return \`${name^}(\${JSON.stringify(this.options)})\`;
  }
}

module.exports = { ${name^} };
JSEOF
            ;;
        ts|typescript)
            cat << TSEOF
interface I${name^} {
  id: string;
  createdAt: Date;
  updatedAt: Date;
}

class ${name^} implements I${name^} {
  id: string;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<I${name^}> = {}) {
    this.id = data.id || crypto.randomUUID();
    this.createdAt = data.createdAt || new Date();
    this.updatedAt = data.updatedAt || new Date();
  }

  toJSON(): I${name^} {
    return { id: this.id, createdAt: this.createdAt, updatedAt: this.updatedAt };
  }

  validate(): boolean {
    return !!this.id;
  }
}

export { ${name^}, I${name^} };
TSEOF
            ;;
        go|golang)
            cat << GOEOF
package main

import (
	"encoding/json"
	"fmt"
	"time"
)

type ${name^} struct {
	ID        string    \`json:"id"\`
	CreatedAt time.Time \`json:"created_at"\`
}

func New${name^}() *${name^} {
	return &${name^}{
		ID:        fmt.Sprintf("%d", time.Now().UnixNano()),
		CreatedAt: time.Now(),
	}
}

func (m *${name^}) ToJSON() ([]byte, error) {
	return json.Marshal(m)
}

func (m *${name^}) String() string {
	return fmt.Sprintf("${name^}{ID: %s}", m.ID)
}
GOEOF
            ;;
        java)
            cat << JAVAEOF
public class ${name^} {
    private String id;
    private java.time.Instant createdAt;

    public ${name^}() {
        this.id = java.util.UUID.randomUUID().toString();
        this.createdAt = java.time.Instant.now();
    }

    public String getId() { return id; }
    public java.time.Instant getCreatedAt() { return createdAt; }

    @Override
    public String toString() {
        return "${name^}{id=" + id + ", createdAt=" + createdAt + "}";
    }
}
JAVAEOF
            ;;
        *) echo "Languages: python, javascript, typescript, go, java" ;;
    esac
    _log "class" "$name ($lang)"
}

cmd_api() {
    local name="${1:?Usage: code-generator api <name> [framework]}"
    local fw="${2:-fastapi}"
    
    case "$fw" in
        fastapi|fast)
            cat << APIEOF
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional
import uuid

app = FastAPI(title="${name^} API")

class ${name^}(BaseModel):
    id: str = ""
    name: str
    
class ${name^}Create(BaseModel):
    name: str

db: dict = {}

@app.get("/${name}s", response_model=List[${name^}])
def list_items():
    return list(db.values())

@app.get("/${name}s/{item_id}", response_model=${name^})
def get_item(item_id: str):
    if item_id not in db:
        raise HTTPException(404, "Not found")
    return db[item_id]

@app.post("/${name}s", response_model=${name^}, status_code=201)
def create_item(item: ${name^}Create):
    new = ${name^}(id=str(uuid.uuid4()), name=item.name)
    db[new.id] = new
    return new

@app.delete("/${name}s/{item_id}", status_code=204)
def delete_item(item_id: str):
    if item_id not in db:
        raise HTTPException(404, "Not found")
    del db[item_id]
APIEOF
            ;;
        express)
            cat << EXEOF
const express = require('express');
const { v4: uuid } = require('uuid');
const app = express();
app.use(express.json());

const db = new Map();

app.get('/${name}s', (req, res) => {
  res.json([...db.values()]);
});

app.get('/${name}s/:id', (req, res) => {
  const item = db.get(req.params.id);
  if (!item) return res.status(404).json({ error: 'Not found' });
  res.json(item);
});

app.post('/${name}s', (req, res) => {
  const item = { id: uuid(), ...req.body, createdAt: new Date() };
  db.set(item.id, item);
  res.status(201).json(item);
});

app.delete('/${name}s/:id', (req, res) => {
  if (!db.delete(req.params.id)) return res.status(404).json({ error: 'Not found' });
  res.status(204).end();
});

app.listen(3000, () => console.log('${name^} API on :3000'));
EXEOF
            ;;
        flask)
            cat << FLEOF
from flask import Flask, jsonify, request, abort
import uuid

app = Flask(__name__)
db = {}

@app.route('/${name}s', methods=['GET'])
def list_items():
    return jsonify(list(db.values()))

@app.route('/${name}s/<item_id>', methods=['GET'])
def get_item(item_id):
    if item_id not in db: abort(404)
    return jsonify(db[item_id])

@app.route('/${name}s', methods=['POST'])
def create_item():
    data = request.json
    item = {'id': str(uuid.uuid4()), **data}
    db[item['id']] = item
    return jsonify(item), 201

@app.route('/${name}s/<item_id>', methods=['DELETE'])
def delete_item(item_id):
    if item_id not in db: abort(404)
    del db[item_id]
    return '', 204

if __name__ == '__main__':
    app.run(debug=True)
FLEOF
            ;;
        *) echo "Frameworks: fastapi, express, flask" ;;
    esac
    _log "api" "$name ($fw)"
}

cmd_cli() {
    local name="${1:?Usage: code-generator cli <name> [lang]}"
    local lang="${2:-bash}"
    
    case "$lang" in
        bash|sh)
            cat << CLIEOF
#!/usr/bin/env bash
set -euo pipefail
VERSION="1.0.0"

usage() {
    echo "$name v\$VERSION"
    echo "Usage: $name <command> [options]"
    echo ""
    echo "Commands:"
    echo "  run        Main operation"
    echo "  config     Show configuration"
    echo "  help       Show this help"
}

cmd_run() { echo "Running $name..."; }
cmd_config() { echo "Config: ~/.config/$name/config.yaml"; }

case "\${1:-help}" in
    run) shift; cmd_run "\$@" ;;
    config) cmd_config ;;
    help|-h) usage ;;
    version|-v) echo "$name v\$VERSION" ;;
    *) echo "Unknown: \$1"; usage; exit 1 ;;
esac
CLIEOF
            ;;
        python|py)
            cat << CLIPY
#!/usr/bin/env python3
"""$name — CLI tool."""
import argparse
import sys

def cmd_run(args):
    print(f"Running $name with {args}")

def main():
    parser = argparse.ArgumentParser(description="$name")
    sub = parser.add_subparsers(dest="command")
    sub.add_parser("run", help="Main operation")
    sub.add_parser("config", help="Show config")
    
    args = parser.parse_args()
    if args.command == "run":
        cmd_run(args)
    elif args.command == "config":
        print(f"Config: ~/.config/$name/")
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
CLIPY
            ;;
        *) echo "Languages: bash, python" ;;
    esac
    _log "cli" "$name ($lang)"
}

cmd_model() {
    local name="${1:?Usage: code-generator model <name> <field:type> ...}"
    shift
    
    echo "from dataclasses import dataclass, field"
    echo "from datetime import datetime"
    echo "from typing import Optional"
    echo ""
    echo "@dataclass"
    echo "class ${name^}:"
    echo "    \"\"\"${name^} data model.\"\"\""
    
    for fld in "$@"; do
        local fname="${fld%%:*}"
        local ftype="${fld##*:}"
        case "$ftype" in
            str|string) echo "    $fname: str = \"\"" ;;
            int|integer) echo "    $fname: int = 0" ;;
            float|number) echo "    $fname: float = 0.0" ;;
            bool|boolean) echo "    $fname: bool = False" ;;
            date|datetime) echo "    $fname: Optional[datetime] = None" ;;
            *) echo "    $fname: str = \"\"  # $ftype" ;;
        esac
    done
    
    echo "    created_at: datetime = field(default_factory=datetime.now)"
    echo ""
    echo "    def validate(self) -> bool:"
    echo "        return True"
    _log "model" "$name (${#} fields)"
}

cmd_docker() {
    local lang="${1:-python}"
    case "$lang" in
        python|py)
            cat << DKEOF
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "main.py"]
DKEOF
            ;;
        node|js)
            cat << DKNEOF
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --production
COPY . .
EXPOSE 3000
CMD ["node", "index.js"]
DKNEOF
            ;;
        go|golang)
            cat << DKGEOF
FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/app

FROM alpine:3.19
COPY --from=build /bin/app /bin/app
EXPOSE 8080
ENTRYPOINT ["/bin/app"]
DKGEOF
            ;;
        *) echo "Languages: python, node, go" ;;
    esac
    _log "docker" "$lang"
}

cmd_readme() {
    local project="${1:-my-project}"
    cat << RDEOF
# ${project}

Brief description of ${project}.

## Installation

\`\`\`bash
git clone https://github.com/user/${project}.git
cd ${project}
# install steps
\`\`\`

## Usage

\`\`\`bash
${project} --help
\`\`\`

## Contributing

1. Fork it
2. Create your branch (\`git checkout -b feature/xyz\`)
3. Commit (\`git commit -am 'Add xyz'\`)
4. Push (\`git push origin feature/xyz\`)
5. Open a Pull Request

## License

MIT
RDEOF
    _log "readme" "$project"
}

cmd_gitignore() {
    local lang="${1:-python}"
    case "$lang" in
        python|py)
            echo "__pycache__/"; echo "*.pyc"; echo ".venv/"; echo "dist/"; echo "*.egg-info/"
            echo ".env"; echo ".pytest_cache/"; echo ".mypy_cache/"
            ;;
        node|js|ts)
            echo "node_modules/"; echo "dist/"; echo ".env"; echo "*.log"; echo "coverage/"
            ;;
        go|golang)
            echo "bin/"; echo "vendor/"; echo "*.exe"; echo ".env"
            ;;
        *) echo "Languages: python, node, go" ;;
    esac
    _log "gitignore" "$lang"
}

cmd_config_gen() {
    local fmt="${1:-yaml}"
    case "$fmt" in
        yaml|yml)
            echo "app:"; echo "  name: myapp"; echo "  port: 8080"; echo "  debug: false"
            echo "database:"; echo "  host: localhost"; echo "  port: 5432"; echo "  name: mydb"
            ;;
        toml)
            echo "[app]"; echo 'name = "myapp"'; echo "port = 8080"; echo "debug = false"
            echo ""; echo "[database]"; echo 'host = "localhost"'; echo "port = 5432"
            ;;
        json)
            echo '{"app":{"name":"myapp","port":8080},"database":{"host":"localhost","port":5432}}'
            ;;
        ini)
            echo "[app]"; echo "name = myapp"; echo "port = 8080"
            echo ""; echo "[database]"; echo "host = localhost"; echo "port = 5432"
            ;;
        *) echo "Formats: yaml, toml, json, ini" ;;
    esac
    _log "config" "$fmt"
}

cmd_license() {
    local type="${1:-mit}"
    local year=$(date +%Y)
    case "$type" in
        mit) echo "MIT License"; echo "Copyright (c) $year"; echo ""; echo "Permission is hereby granted..." ;;
        apache) echo "Apache License 2.0"; echo "Copyright $year" ;;
        gpl) echo "GNU General Public License v3.0" ;;
        *) echo "Types: mit, apache, gpl" ;;
    esac
    _log "license" "$type"
}

cmd_history() {
    local log="$DATA_DIR/history.log"
    [ -f "$log" ] && tail -20 "$log" || echo "No history yet."
}

_log() {
    echo "$(date '+%Y-%m-%d %H:%M') | $1 | $2" >> "$DATA_DIR/history.log"
}

case "${1:-help}" in
    class)      shift; cmd_class "$@" ;;
    api)        shift; cmd_api "$@" ;;
    cli)        shift; cmd_cli "$@" ;;
    model)      shift; cmd_model "$@" ;;
    test)       shift; echo "TODO: test generator" ;;
    crud)       shift; echo "TODO: crud generator" ;;
    config)     shift; cmd_config_gen "$@" ;;
    docker)     shift; cmd_docker "$@" ;;
    readme)     shift; cmd_readme "$@" ;;
    gitignore)  shift; cmd_gitignore "$@" ;;
    snippet)    shift; echo "TODO: snippet" ;;
    license)    shift; cmd_license "$@" ;;
    history)    cmd_history ;;
    help|-h)    show_help ;;
    version|-v) echo "code-generator v$VERSION" ;;
    *)          echo "Unknown: $1"; show_help; exit 1 ;;
esac
